spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_app
    username: milkartem
    password: Q1!w2e3r4t5
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_schema: library_app
#        dialect: MySQLDialect

application:
  max-allowed-books: 2
