spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: milkartem
    password: Q1!w2e3r4t5
    driver-class-name:
jpa:
  show-sql: true
  hibernate:
    naming:
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

application:
  max-allowed-books: 2
